language: android
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

licenses:
  - 'android-sdk-preview-license-.+'

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.3
  - echo y | android update sdk -u -a -t android-25
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

android:
  components:
    - build-tools-25.0.3
    - android-25
    - sys-img-armeabi-v7a-android-25